//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC;Initial Catalog=SQL_QUANLYHOCSINH;Integrated Security=True")]
        public string SQL_QUANLYHOCSINHConnectionString1 {
            get {
                return ((string)(this["SQL_QUANLYHOCSINHConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Sky;Initial Catalog=SQL_QUANLYHOCSINH;Integrated Security=True")]
        public string SQL_QUANLYHOCSINHConnectionString2 {
            get {
                return ((string)(this["SQL_QUANLYHOCSINHConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=THINH;Initial Catalog=SQL_QUANLYHOCSINH;Integrated Security=True")]
        public string SQL_QUANLYHOCSINHConnectionString3 {
            get {
                return ((string)(this["SQL_QUANLYHOCSINHConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sky;Initial Catalog=SQL_QUANLYHOCSINH;Integrated Security=True")]
        public string SQL_QUANLYHOCSINHConnectionString4 {
            get {
                return ((string)(this["SQL_QUANLYHOCSINHConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Localhost;Initial Catalog=sql_quanlyhocsinh;Integrated Security=True")]
        public string sql_quanlyhocsinhConnectionString5 {
            get {
                return ((string)(this["sql_quanlyhocsinhConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Localhost;Initial Catalog=SQL_QUANLYHOCSINH;Integrated Security=True")]
        public string SQL_QUANLYHOCSINHConnectionString {
            get {
                return ((string)(this["SQL_QUANLYHOCSINHConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LOCTHO\\LOCTHO;Initial Catalog=sql_quanlyhocsinh;Integrated Security=T" +
            "rue")]
        public string sql_quanlyhocsinhConnectionString6 {
            get {
                return ((string)(this["sql_quanlyhocsinhConnectionString6"]));
            }
        }
    }
}
